achievements/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^apr/(?P<pk>[0-9]+)/$', views.AppraisalDetailView.as_view(), name='appraisal_detail'),
	url(r'^apra/(?P<pk>[0-9]+)/$', views.AppraDetail.as_view(), name='aprr_detail'),
	url(r'^qn/(?P<pk>[0-9]+)/$', views.QuestionDetailView.as_view(), name='question_detail'),
	url(r'^$', views.AppraisalListView.as_view(), name='appraisal_list'),
	url(r'^q/fm/$', views.QnView.as_view(), name='qn_fm'),
	url(r'^qn/$', views.QuestionListView.as_view(), name='question_list'),
	url(r'^qn/create/$', views.QuestionCreateView.as_view(), name='question_create'),
	url(r'^a/create/$', views.AppraisalCreateView.as_view(), name='appraisal_create'),
	url(r'^qn/manage/$', views.manage_questions, name='manage_questions'),
	url(r'^qn/f/$', views.profile_settings, name='profile_settings'),
	url(r'^profile/$', views.ProfileList.as_view(), name='profile'),
	url(r'^profile/f/$', views.ProfileFamilyMemberCreate.as_view(), name='profile_f'),
]

appraisal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from achievements.views import review
from django.conf import settings
from django.conf.urls.static import static

# from achievements import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^review/$', review, name='review'),
    url(r'^appraisal/', include('achievements.urls', namespace='appraisal')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

achievements/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib import admin

User = settings.AUTH_USER_MODEL


class Profile(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    created_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
         return ('%s %s' % (self.first_name , self.last_name))


class FamilyMember(models.Model):
    profile = models.ForeignKey(Profile)
    name = models.CharField(max_length=100)
    relationship = models.CharField(max_length=100)

    def __str__(self):
        return self.profile.first_name

class UserLink(models.Model):
	anchor = models.CharField(max_length=10000, null=True, blank=True)
	url = models.CharField(max_length=10000, null=True, blank=True)
	user = models.ForeignKey(User, null=True, blank=True)

	def __str__(self):
		return self.anchor

admin.site.register(Profile)
admin.site.register(FamilyMember)
admin.site.register(UserLink)

class Employee(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	RANK_CHOICES = ('JR','Junior'),('SP','Superior'),('HR','Human Resource')
	rank = models.CharField(max_length=2, default='JR', choices=RANK_CHOICES)

	def __str__(self):
		return ('{0} -- {1}'.format(self.rank, self.user.username))


class Appraisal(models.Model):
	employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='employee')
	superior = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='superior')
	# question = models.ManyToManyField(Question)
	total = models.PositiveIntegerField()
	created = models.DateField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return self.employee.user.username + ' ' + str(self.created)

	def get_absolute_url(self):
		return reverse('appraisal:appraisal_detail', kwargs={'pk': self.pk})


class Question(models.Model):
	appraisal = models.ForeignKey(Appraisal, on_delete=models.CASCADE, null=True, blank=True)
	title = models.CharField(max_length=300)
	description = models.CharField(max_length=300)
	ONE = 1
	TWO = 2
	THREE = 3
	FOUR = 4
	FIVE = 5
	RANK =(ONE, 1),(TWO, 2),(THREE, 3),(FOUR, 4),(FIVE, 5),

	rank = models.IntegerField(choices=RANK, default=ONE)
	created = models.DateField(auto_now_add=True)


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('appraisal:question_detail', kwargs={'pk': self.pk})

achievements/forms.py
from django import forms
from .models import Question, Employee, Appraisal

class QnForm(forms.ModelForm):
	description = forms.CharField(
		widget=forms.TextInput(attrs={'class': 'form-control'}),
		max_length=250,
		required=False)

	class Meta:
		model = Question
		fields = ['appraisal', 'title', 'description', 'rank']


class ReviewForm(forms.ModelForm):
	question = forms.CharField(
		widget=forms.TextInput(attrs={'class': 'form-control'}),
		max_length=50,
		required=False)

	class Meta:
		model = Appraisal
		fields = ['employee']


class QuestionForm(forms.ModelForm):
	description = forms.CharField(
		widget=forms.TextInput(attrs={'class': 'form-control'}),
		max_length=250,
		required=False)

	class Meta:
		model = Question
		fields = ['appraisal', 'title', 'description', 'rank']


class LinkForm(forms.Form):
    """
    Form for individual user links
    """
    anchor = forms.CharField(
                    max_length=100,
                    widget=forms.TextInput(attrs={
                        'placeholder': 'Link Name / Anchor Text',
                    }),
                    required=False)
    url = forms.URLField(
                    widget=forms.URLInput(attrs={
                        'placeholder': 'URL',
                    }),
                    required=False)


class ProfileForm(forms.Form):
    """
    Form for user to update their own profile details
    (excluding links which are handled by a separate formset)
    """
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ProfileForm, self).__init__(*args, **kwargs)

        self.fields['first_name'] = forms.CharField(
                                        max_length=30,
                                        initial = self.user.first_name,
                                        widget=forms.TextInput(attrs={
                                            'placeholder': 'First Name',
                                        }))
        self.fields['last_name'] = forms.CharField(
                                        max_length=30,
                                        initial = self.user.last_name,
                                        widget=forms.TextInput(attrs={
                                            'placeholder': 'Last Name',
                                        }))


from django.forms.formsets import BaseFormSet

class BaseLinkFormSet(BaseFormSet):
    def clean(self):
        """
        Adds validation to check that no two links have the same anchor or URL
        and that all links have both an anchor and URL.
        """
        if any(self.errors):
            return

        anchors = []
        urls = []
        duplicates = False

        for form in self.forms:
            if form.cleaned_data:
                anchor = form.cleaned_data['anchor']
                url = form.cleaned_data['url']

                # Check that no two links have the same anchor or URL
                if anchor and url:
                    if anchor in anchors:
                        duplicates = True
                    anchors.append(anchor)

                    if url in urls:
                        duplicates = True
                    urls.append(url)

                if duplicates:
                    raise forms.ValidationError(
                        'Links must have unique anchors and URLs.',
                        code='duplicate_links'
                    )

                # Check that all links have both an anchor and URL
                if url and not anchor:
                    raise forms.ValidationError(
                        'All links must have an anchor.',
                        code='missing_anchor'
                    )
                elif anchor and not url:
                    raise forms.ValidationError(
                        'All links must have a URL.',
                        code='missing_URL'
                    )
from .models import FamilyMember, Profile
class FamilyMemberForm(forms.ModelForm):
    class Meta:
        model = FamilyMember
        exclude = ()

FamilyMemberFormSet = forms.inlineformset_factory(Profile, FamilyMember,
                                            form=FamilyMemberForm, extra=1)

achievements/views.py
from django.contrib.auth.decorators import login_required
from .forms import ReviewForm, QuestionForm
from django.contrib import messages
from django.views.generic import DetailView, ListView, CreateView
from .models import Question, Employee, Appraisal
from django.conf import settings
from django.forms import formset_factory, modelformset_factory
from django.shortcuts import render, redirect

User = settings.AUTH_USER_MODEL

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.db import IntegrityError, transaction
from django.forms.formsets import formset_factory
from django.shortcuts import redirect, render
from .forms import LinkForm, BaseLinkFormSet, ProfileForm, FamilyMemberFormSet, QnForm
from .models import UserLink, Profile
from django.views.generic.edit import FormView
from django.urls import reverse
from django.http import HttpResponseForbidden
from django.views.generic import FormView
from django.views.generic.detail import SingleObjectMixin
from django.views import View


class AppraDisplay(DetailView):
    model = Appraisal
    template_name = 'achievements/form_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AppraDisplay, self).get_context_data(**kwargs)
        context['form'] = QnForm()
        return context

class ApprFormView(SingleObjectMixin, FormView):
    template_name = 'achievements/form_detail.html'
    form_class = QnForm
    model = Question
    success_url = reverse_lazy()

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        self.object.save()
        return super(ApprFormView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return super(ApprFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('appraisal:question_detail', kwargs={'pk': self.object.pk})


class AppraDetail(View):

    def get(self, request, *args, **kwargs):
        view = AppraDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ApprFormView.as_view()
        return view(request, *args, **kwargs)


class QnView(FormView):
    template_name = 'achievements/qn_fm.html'
    success_url = '/appraisal/qn/'
    form_class = QnForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return super(QnView, self).form_valid(form)


class ProfileList(ListView):
    model = Profile


class ProfileFamilyMemberCreate(CreateView):
    model = Profile
    fields = ['first_name', 'last_name']
    success_url = reverse_lazy('appraisal:profile')

    def get_context_data(self, **kwargs):
        data = super(ProfileFamilyMemberCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['familymembers'] = FamilyMemberFormSet(self.request.POST)
        else:
            data['familymembers'] = FamilyMemberFormSet()
        return data


    def form_valid(self, form):
        context = self.get_context_data()
        familymembers = context['familymembers']
        with transaction.atomic():
            self.object = form.save()

            if familymembers.is_valid():
                familymembers.instance = self.object
                familymembers.save()
        return super(ProfileFamilyMemberCreate, self).form_valid(form)


@login_required
def profile_settings(request):
    """
    Allows a user to update their own profile.
    """
    user = request.user

    # Create the formset, specifying the form and formset we want to use.
    LinkFormSet = formset_factory(LinkForm, formset=BaseLinkFormSet)

    # Get our existing link data for this user.  This is used as initial data.
    user_links = UserLink.objects.filter(user=user).order_by('anchor')
    link_data = [{'anchor': l.anchor, 'url': l.url}
                    for l in user_links]

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, user=user)
        link_formset = LinkFormSet(request.POST)

        if profile_form.is_valid() and link_formset.is_valid():
            # Save user info
            user.first_name = profile_form.cleaned_data.get('first_name')
            user.last_name = profile_form.cleaned_data.get('last_name')
            user.save()

            # Now save the data for each form in the formset
            new_links = []

            for link_form in link_formset:
                anchor = link_form.cleaned_data.get('anchor')
                url = link_form.cleaned_data.get('url')

                if anchor and url:
                    new_links.append(UserLink(user=user, anchor=anchor, url=url))

            try:
                with transaction.atomic():
                    #Replace the old with the new
                    UserLink.objects.filter(user=user).delete()
                    UserLink.objects.bulk_create(new_links)

                    # And notify our users that it worked
                    messages.success(request, 'You have updated your profile.')

            except IntegrityError: #If the transaction failed
                messages.error(request, 'There was an error saving your profile.')
                return redirect(reverse('profile-settings'))

    else:
        profile_form = ProfileForm(user=user)
        link_formset = LinkFormSet(initial=link_data)

    context = {
        'profile_form': profile_form,
        'link_formset': link_formset,
    }

    return render(request, 'achievements/edit_profile.html', context)

def manage_questions(request):
    QuestionFormSet = modelformset_factory(Question, fields=['appraisal', 'title', 'description', 'rank'], extra=3)
    if request.method == 'POST':
        formset = QuestionFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            return redirect('appraisal:profile_f')
    else:
        formset = QuestionFormSet()
    return render(request, 'achievements/question_formset.html', {'formset': formset})


@login_required
def review(request):
    user = request.user
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review.user = form.cleaned_data.get('user')
            review.question.title = form.cleaned_data.get('question')
            review.employe = request.user
            review.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your review was successfully edited.')

    else:
        form = ReviewForm(instance=user, initial={
            'employee': user,
            })
    return render(request, 'achievements/review_add.html', {'form': form})


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'achievements/qn_detail.html'

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        # context['user_list'] = User.objects.all()
        # context['appraisal_list'] = Appraisal.objects.all()
        return context


class QuestionListView(ListView):
    model = Question
    template_name = 'achievements/question_list.html'


class AppraisalDetailView(DetailView):
    model = Appraisal
    template_name = 'achievements/apr_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AppraisalDetailView, self).get_context_data(**kwargs)
        # context['user_list'] = User.objects.all()
        context['question_list'] = Question.objects.filter(appraisal=self.kwargs['pk'])
        context['form'] = QnForm
        return context



class AppraisalListView(ListView):
    model = Appraisal
    template_name = 'achievements/appraisal_list.html'


# @parsleyfy
class QuestionCreateView(CreateView):
    model = Question
    fields = ['title', 'description','appraisal', 'rank', ]
    # template_name = 'achievements/new_.html'

# @parsleyfy
class AppraisalCreateView(CreateView):
    model = Appraisal
    fields = ['employee', 'superior', 'total']
    template_name = 'achievements/appraisal_form.html'

achievements/templates/achievements/appraisal_form.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>


</head>
<body style="margin-left: 100px; margin-right: 100px;">
<h4>Hello world</h4>
<form action="" method="post" role="form">
    {% csrf_token %}
     {{ form.as_p }}
  <button type="submit" class="btn waves-effect waves-light light-blue darken-4">Submit</button>

</form>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

{#<script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>#}
{#{% include 'material/includes/material_js.html' %}#}

</body>
</html>

achievements/templates/achievements/appraisal_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<p>{% for apr in appraisal_list %}
    <a href="{{ apr.get_absolute_url }}">{{ apr }}</a><br>
    {% endfor %}
</p>
</body>
</html>

achievements/templates/achievements/apr_detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body style="margin-left: 200px;">
<h1>{{ object.employee.user.username }}</h1>
<p>Appraisal done on {{ object.created }}</p>

    <table border="1">
    <thead>
      <tr>
        <th></th>
        <th>Question</th>
        <th>Description</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      {% for qn in question_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
            <td><a href="{{ qn.get_absolute_url }}">{{ qn.title }}</a></td>
          <td>{{ qn.description }}</td>
          <td>{{ qn.rank }}</td>
        </tr>
        {% if forloop.last %}
          <tr>
            <td colspan="3">
              TOTAL
            </td>
          <td>{{ object.total }}</td>
          </tr>
        {% endif %}
      {% empty %}
        <tr>
          <td colspan="3">No queations</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
<form data-parsley-validate action="{% url 'appraisal:qn_fm' %}" method="post" role="form">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit" class="btn waves-effect waves-light light-blue darken-4">Submit</button>
</form>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/parsley.min.js' %}"></script>
</body>
</html>

achievements/templates/achievements/edit_profile.html
{% load staticfiles %}

{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}

    <label>First Name</label>
    {{ profile_form.first_name }}
    {% if profile_form.first_name.errors %}
        {% for error in profile_form.first_name.errors %}
            {{ error|escape }}
        {% endfor %}
    {% endif %}

    <label>Last Name</label>
    {{ profile_form.last_name }}
    {% if profile_form.last_name.errors %}
        {% for error in profile_form.last_name.errors %}
            {{ error|escape }}
        {% endfor %}
    {% endif %}

    {{ link_formset.management_form }}

    {% for link_form in link_formset %}
        <div class="link-formset">
            {{ link_form.anchor }}
            {% if link_form.anchor.errors %}
                {% for error in link_form.anchor.errors %}
                    {{ error|escape }}
                {% endfor %}
            {% endif %}

            {{ link_form.url }}
            {% if link_form.url.errors %}
                {% for error in link_form.url.errors %}
                    {{ error|escape }}
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}

    {% if link_formset.non_form_errors %}
        {% for error in link_formset.non_form_errors %}
            {{ error|escape }}
        {% endfor %}
    {% endif %}

    <input type="submit" value="Update Profile" class="button"/>
</form>

<!-- Include formset plugin - including jQuery dependency -->
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script>
    $('.link-formset').formset({
        addText: 'add link',
        deleteText: 'remove'
    });
</script>

achievements/templates/achievements/form_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h3>Hello world !!</h3>
<h5>{{ appraisal }}</h5>
<p>Superior : {{ appraisal.superior }}</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit" class="btn waves-effect waves-light light-blue darken-4">Submit</button>
</form>
</body>
</html>

achievements/templates/achievements/profile_form.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div class="col-md-4">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}

        <table class="table">
            {{ familymembers.management_form }}

            {% for form in familymembers.forms %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                            <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
{#                <tr class="{% cycle row1,row2 %} formset_row">#}
                <tr class="formset_row">
                    {% for field in form.visible_fields %}
                        <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Save"/> <a href="{% url 'appraisal:profile_f' %}">back to the list</a>
    </form>
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'add family member',
        deleteText: 'remove',
        prefix: 'familymember_set'
    });
</script>
</body>
</html>

achievements/templates/achievements/profile_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% for profile in profile_list %}
    {{ profile.first_name }} {{ profile.last_name }} <br>
{% endfor %}

</body>
</html>

achievements/templates/achievements/qn_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<>
<h1>{{ object }}</h1>
<p>hello world!!</p>
</body>
</html>

achievements/templates/achievements/qn_fm.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h3>Hello World !!!</h3>
<form data-parsley-validate action="" method="post" role="form">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit" class="btn waves-effect waves-light light-blue darken-4">Submit</button>
</form>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/parsley.min.js' %}"></script>
</body>
</html>

achievements/templates/achievements/question_form.html
{#{% load static material_form %}#}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
{#    {% include 'material/includes/material_css.html' %}#}

</head>
<body style="margin-left: 100px; margin-right: 100px;">
<h4>Hello world</h4>
<form action="" method="post" role="form">
    {% csrf_token %}
    {{ form.as_p }}
{#    {% form form=form %}#}
{#        {% part form.rank prefix %}<div class="input-group-addon">@</div>{% endpart %}#}
{#    {% endform %}#}
  <button type="submit"  class="btn waves-effect waves-light light-blue darken-4">Submit</button>

</form>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

<script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
{#{% include 'material/includes/material_js.html' %}#}

</body>
</html>

achievements/templates/achievements/question_formset.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form method="post" action="">
    {{ formset.management_form }}
{% csrf_token %}
    <table>
        {% for form in formset %}
        {{ form }}
        {% endfor %}
    </table>
<button type="submit">Submit</button>

</form>

</body>
</html>

achievements/templates/achievements/question_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>{{ object }}</h2>
{% for qn in question_list %}
    <h5><a href="{{ qn.get_absolute_url }}">{{ qn }}</a></h5>
{% endfor %}

<h4>hello world!!</h4>
</body>
</html>

achievements/templates/achievements/review_add.html
{% load static i18n %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">Review</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'review' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>

      </form>
</body>
</html>